import { getSupabaseClient } from "@/lib/supabase";

// Minutes we assume each generated piece of copy saves a human.
export const MINUTES_PER_PIECE = 5;

export interface Analytics {
  totalGenerations: number;
  seoCount: number; // one SEO description per generation
  socialCount: number; // sum of social posts across generations
  emailCount: number; // not generated by this tool yet — shown for completeness
  totalPieces: number;
  minutesSaved: number;
}

interface Row {
  social_posts: unknown;
}

export async function getAnalytics(): Promise<Analytics> {
  const { data, error } = await getSupabaseClient()
    .from("content_generations")
    .select("social_posts")
    .limit(5000);

  if (error) throw new Error(error.message);

  const rows = (data ?? []) as Row[];
  const seoCount = rows.length;
  const socialCount = rows.reduce(
    (sum, r) => sum + (Array.isArray(r.social_posts) ? r.social_posts.length : 0),
    0
  );
  const emailCount = 0;
  const totalPieces = seoCount + socialCount + emailCount;

  return {
    totalGenerations: rows.length,
    seoCount,
    socialCount,
    emailCount,
    totalPieces,
    minutesSaved: totalPieces * MINUTES_PER_PIECE,
  };
}
